<?php

/**
 * @file
 * Contains alloy_file_browser.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function alloy_file_browser_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the alloy_file_browser module.
    case 'help.page.alloy_file_browser':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Alloy file browser tweaks') . '</p>';
      return $output;

    default:
  }
}
